# ======================== FASTQ READS ========================

fastq_dir: reads

# FASTQ file extension: "fastq.gz" or "fastq" or "fq.gz" or "fq", etc.
fastq_ext: "fastq.gz"

# ======================== TRIM READS ========================
#trim_reads: True
trim_reads: False

# ======================== Alignment ========================
# UCSC genome: e.g. hg19, hg38, mm9, mm10, ..
genome: hg19

# ======================== MACS2 ========================
# MACS2 Narrow:
macs2_mode: narrow
macs2_params: "-q 1E-10"
macs2_suffix: q1E-10 # do not use underscores here otherwise wrong sample wildcards

# ======================== SICER ========================
sicer_fragment: 150
sicer_window: 200
sicer_gap: 600
sicer_fdr: 1E-10
sicer_evalue: 100

# ======================== SPAN ========================
span_bin: 200
span_gap: 5
span_fdr: 1E-10
span_markup: ""